raw_data_dir: data/raw
interim_data_dir: data/interim
processed_data_dir: data/processed
split_data_dir: data/splits
report_figures_dir: reports/figures
report_tables_dir: reports/tables
documentation_dir: docs
